//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp24
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesInfo
    {
        public int ID { get; set; }
        public string MaritalStatus { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
